### ISSUE TITLE
Integrating Travis CI (for Chrome plugin)

### ISSUE THREAD

**Issue by federico-code** [collab-uniba/qavmentor-plugin#6]

**Comment by lanubile** [comment]
Completare con il continous deployment in forma di release su GitHub

**Comment by bateman** [comment]
https://www.neowin.net/news/google-is-limiting-chrome-extension-installation-to-the-chrome-web-store

Google is going to disable the sideloading of any chrome extension that is not in the web store

**Comment by bateman** [comment]
https://circleci.com/blog/continuously-deploy-a-chrome-extension/

**Comment by federico-code** [comment]
Confermato l'uso di Travis CI.
Risorse utilizzate:
https://docs.travis-ci.com/user/environment-variables/
https://dev.to/gokatz/automate-your-chrome-extension-deployment-in-minutes-48gb
